### PR TITLE
Fix the name of augroup

### PR DESCRIPTION
**Pull request by itchyny**
This pull request fixes the names of the augroup.

### CODE REVIEW

**Comment by eagletmt** [comment]
Thanks!

**Comment by itchyny** [comment]
Thanks for merging!

**Comment by Shougo** [comment]
I improved the routine.  Thanks.

**Comment by itchyny** [comment]
Hmm, the function `necoghc#boot()` is called in `necoghc#omnifunc()`. Is it intended?

**Comment by itchyny** [comment]
Also I noticed that `InsertLeave *` should be buffer local event.

**Comment by Shougo** [comment]
> Also I noticed that InsertLeave * should be buffer local event.

Thanks.  But if I tested it, it printed error message.

**Comment by Shougo** [comment]
> Hmm, the function necoghc#boot() is called in necoghc#omnifunc(). Is it intended?

Thanks.  I improved it.

**Comment by itchyny** [comment]
I confirmed the latest changes fix the problems! Thank you @eagletmt and @Shougo.

**Pull request merged**
